# Generated by Django 5.1.6 on 2025-02-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='acces',
            field=models.CharField(choices=[('any', 'Anyone'), ('email_requirement', 'Email requirement')], default='email_requirement', max_length=50),
        ),
    ]
