# Generated by Django 5.1.6 on 2025-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_acces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='acces',
            field=models.CharField(choices=[('any', 'Anyone'), ('email', 'Email requirement')], default='email', max_length=5),
        ),
    ]
