# Generated by Django 5.1.6 on 2025-02-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_publick_id_course_timestamp_course_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='publick_id',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
